version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///app/db/partners.db
      - OUTPUT_FILE=/app/assets/output.csv
    volumes:
      - .:/app
